### PR TITLE
Change the style of the button

### PR DESCRIPTION
**Pull request by Csedge**
Add the bootstrap and led the button more beautiful

### CODE REVIEW

**Comment by rise3n** [comment]
can't merge conflict with css and index.html

**Comment by Csedge** [comment]
> can't merge conflict with css and index.html

I solved it

**Comment by Csedge** [comment]
Pls give me a revirew

**Comment by Bienfu** [comment]
Like what you did with the buttons to make them look nicer. However, the setup phase icon ins't a button so you should revert those changes as it also messes up the legend that I made. Additionally, you can get rid of the vertical checkbox button in the ui elements because it isn't necessary anymore. After which we should fix the banner so that it isn't overlapping, but otherwise looks good.

**Comment by Csedge** [comment]
> Like what you did with the buttons to make them look nicer. However, the setup phase icon isn't a button so you should revert those changes as it also messes up the legend that I made. Additionally, you can get rid of the vertical checkbox button in the shiptype elements because it isn't necessary anymore due to the change in right click functionality. After which we should fix the banner so that it isn't overlapping, but otherwise looks good.

I change it back

**Comment by Bienfu** [comment]
Ok, now just change the width of the phase identifier back to 150 and get rid of the input vertical thing in the html file below the place ship buttons and then it looks good to merge

**Comment by Csedge** [comment]
> Ok, now just change the width of the phase identifier back to 150 and get rid of the input vertical thing in the html file below the place ship buttons and then it looks good to merge

OK Done...Megre now. If need any change I will merge manually to next commit

**Pull request merged**
