### PR TITLE
Sonar add

### PR DESCRIPTION
**Pull request by Csedge**
Complete the sonar implenment,Only need to change the number on the Sonar buttom,I donot know how to change it by using the JS,so I alert the remain_sonar  and result on screen.Please give me the merge，this is test success.And i Also add a test on my feature

### CODE REVIEW

**Comment by Csedge** [comment]
Yes a i only alert it to the user if it is exist a ship on the map

**Comment by Csedge** [comment]
Empty is not ship and exist means it have ship

**Comment by hcmlax** [comment]
ok, so we just need to change it to look over a section of the map that the user selects, like what the assignment page shows

**Comment by rise3n** [comment]
it seems that only one grid is checked.

**Comment by Bienfu** [comment]
and then it doesn't display the result on the boxes it does check.

**Pull request merged**
