### PR TITLE
Sprint3 csedge dev

### PR DESCRIPTION
**Pull request by Csedge**
The #51 PR have bug,so it can not place ship. I was complete the implent of sonar pause

### CODE REVIEW

**Comment by Bienfu** [comment]
I looked at the code, but I haven't been able to get the pulse to work using the methods described in an assignment. I tried after sinking 1 ship and after sinking 2 ships but haven't been able to get it to work.

**Comment by Csedge** [comment]
> I looked at the code, but I haven't been able to get the pulse to work using the methods described in an assignment. I tried after sinking 1 ship and after sinking 2 ships but haven't been able to generate the pulse or the hover effects showing that you are about to use it.



> I looked at the code, but I haven't been able to get the pulse to work using the methods described in an assignment. I tried after sinking 1 ship and after sinking 2 ships but haven't been able to generate the pulse or the hover effects showing that you are about to use it.

Please merge this first, I am working on fixed it

**Comment by Csedge** [comment]
This bug it not from me....

**Comment by Csedge** [comment]
OK  I merge your code and let it work together now

**Pull request merged**
